# Generated by Django 4.0.3 on 2022-04-25 21:26

from django.db import migrations


statuses = ["SUBMITTED", "APPROVED", "REJECTED"]


def up(apps, schema):
    Status = apps.get_model("presentations", "Status")
    for id, status in enumerate(statuses):
        Status.objects.create(
            id=id,
            name=status,
        )


def down(apps, schema):
    Status = apps.get_model("presentations", "Status")
    Status.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(up, down)
    ]
